# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# https://docs.travis-ci.com/user/multi-os/
# https://ropensci.org/blog/blog/2016/07/12/travis-osx

language: r
sudo: false
cache: packages
warnings_are_errors: true

r:
 - release
 - devel
 - oldrel

r_binary_packages:
 - Rcpp
 - testthat
 - devtools
 - LaplacesDemon
 - evd
 - hoa
 - skellam
 - triangle
 - actuar
 - covr
 
 r_packages:
  - VGAM
 
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3
before_install:
 - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

notifications:
  email:
    on_success: change
    on_failure: change
    
after_success:
 - Rscript -e 'library(covr); codecov()'
